services:
  db:
    image: postgres:17.6-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${AMARTHA_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${AMARTHA_DATABASE_PASSWORD}
      POSTGRES_DB: ${AMARTHA_DATABASE_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
